# Generated by Django 4.2.2 on 2023-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sale',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('e', 'Electronics'), ('c', 'Clothing'), ('f', 'Furniture'), ('g', 'Grocery'), ('f', 'Food')], default='e', max_length=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
