# Generated by Django 4.2.2 on 2023-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_products_gender_remove_products_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('e', 'Electronics'), ('c', 'Clothing'), ('f', 'Furniture'), ('g', 'Grocery')], default='e', max_length=3),
        ),
    ]
